### ISSUE TITLE
draw fbo to second window

### ISSUE THREAD

**Issue by kimasendorf** [genekogan/ofxSecondWindow#5]
I am drawing a fbo to the second window which works well if the window is 1024x768px. when i change the window size to i.e. 1280x720px the fbo gets displayed in weird dimensions.

I initialize the fbo with the exact same pixel size as the second window dimensions and simply draw it like this:

secondWindow.begin();
fbo.draw(0, 0);
secondWindow.end();</code>

Any ideas? =)

**Comment by kimasendorf** [comment]
Just figured out that it has something to do with the window size of the main window as specified in main.cpp. When both are equal the fbo renders fine..

**Comment by genekogan** [comment]
i'm not able to reproduce this problem. can you post your code?
it's also worth noting that ofxSecondWindow will be obsolete in the next release of openframeworks which will support multiple windows by default. you can already use it from the nightly build.

**Comment by kimasendorf** [comment]
oh really, is there an example out there?

**Comment by kimasendorf** [comment]
found it, thx for the hint !
